### ISSUE TITLE
duplicated fundid

### ISSUE THREAD

**Issue by yakiang** [szpnygo/iOS-fundmoney-swift#1]
苏宁 零钱宝 和 网易 现金宝 `fundid` 一样，是本来就这样还是 typo ?

**Comment by szpnygo** [comment]
网易现金宝是 汇添富现金宝货币基金( 基金代码 000330 )
苏宁零钱包有A和B两个，一个广发天天红货币基金000389，一个是汇添富现金宝基金，和网易一样。
https://licai.suning.com/bof/licaiIndex.htm
